[variables]
PHP_VERSION = '8.1'

[phases.setup]
nixPkgs = ['php81']

[phases.build]
cmds = [
    'composer install --no-dev --ignore-platform-reqs --no-scripts --optimize-autoloader',
    'composer dump-autoload --optimize',
    'npm ci && npm run build'
]

[start]
cmd = 'vendor/bin/heroku-php-apache2 public/'
